services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf # Configuración personalizada
      - mosquitto_data:/mosquitto/data # Persistencia de datos
      - mosquitto_logs:/mosquitto/log # Logs
    networks:
      - container-network
  python-consumer:
    build: ./python-consumer
    container_name: python-consumer
    volumes:
      - ~/huertodb:/db
    networks:
      - container-network

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local

networks:
  container-network:
    driver: bridge