services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf # Configuración personalizada
      - mosquitto_data:/mosquitto/data # Persistencia de datos
      - mosquitto_logs:/mosquitto/log # Logs
    networks:
      - container-network
  python-consumer:
    build: ./python-consumer
    container_name: python-consumer
    depends_on:
      - mosquitto
    restart: always
    volumes:
      - ~/huertodb:/db
    networks:
      - container-network
  web-app:
    build: ./web-app
    container_name: web-app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ~/huertodb:/db
    networks:
      - container-network

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local

networks:
  container-network:
    driver: bridge